laser_scan_matcher:
  fixed_frame: "odom"
  base_frame: "base_link"

  use_imu: true
  use_odom: true

  # kf_dist_linear: 0.10
  # kf_dist_angular: 0.175

  publish_pose_with_covariance_stamped: true

  # do_compute_covariance: true

  position_covariance: [
    0.01, 0.01, 0.0 # x y
  ]

  orientation_covariance: [
    0.0, 0.0, 0.1 # YAW
  ]
