pose_stamped_covariance: [
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
]

pose_covariance: [
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0,
]

twist_covariance: [
  0.3, 0,   0,  0,  0,  0,
  0,   0.3, 0,  0,  0,  0,
  0,   0,   0,  0,  0,  0,
  0,   0,   0,  0,  0,  0,
  0,   0,   0,  0,  0,  0,
  0,   0,   0,  0,  0,  0.3,
]